name: PR JSON Validator

on:
  pull_request:
    paths:
      - "API/**/*.json"
  push:
    paths:
      - "API/**/*.json"
  workflow_dispatch:

env:
  GitHubMail: "ascpbot128@gmail.com"
  GitHubName: "TheASCPBot"
  GitHubToken: ${{ secrets.GH_TOKEN }}

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run JSON Validator
        run: python scripts/validate_json.py
